
const constants = {
  INCREMENT:"INCREMENT",
  DECREMENT:"DECREMENT",
  POST_BOOK:"POST_BOOK",
  DELETE_BOOK:"DELETE_BOOK",
  UPDATE_BOOK:"UPDATE_BOOK",
  ADD_TO_CART:"ADD_TO_CART",
  GET_BOOKS:"GET_BOOKS",
  DELETE_CART_ITEM: "DELETE_CART_ITEM",
  UPDATE_CART: "UPDATE_CART",
  TOTAL_AMOUNT: "TOTAL_AMOUNT"
};

export default constants;
